// <auto-generated />
using System;
using EmployeeManager.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManager.API.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HiringDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            HiringDate = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            HiringDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            HiringDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            HiringDate = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("RewardRate")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RewardRate = 50.0,
                            Title = "Software Developer"
                        },
                        new
                        {
                            Id = 2,
                            RewardRate = 70.0,
                            Title = "Project Manager"
                        },
                        new
                        {
                            Id = 3,
                            RewardRate = 60.0,
                            Title = "Data Analyst"
                        },
                        new
                        {
                            Id = 4,
                            RewardRate = 55.0,
                            Title = "UX Designer"
                        },
                        new
                        {
                            Id = 5,
                            RewardRate = 65.0,
                            Title = "System Administrator"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 5,
                            EmployeeId = 2,
                            Message = "Excellent performance",
                            Rate = 250.0
                        },
                        new
                        {
                            Id = 2,
                            Count = 3,
                            EmployeeId = 3,
                            Message = "Great leadership",
                            Rate = 210.0
                        },
                        new
                        {
                            Id = 3,
                            Count = 4,
                            EmployeeId = 4,
                            Message = "Outstanding teamwork",
                            Rate = 300.0
                        });
                });

            modelBuilder.Entity("DataLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admin",
                            IsAdmin = true,
                            LastName = "User",
                            Password = "adminpassword",
                            Username = "adminuser"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "John",
                            IsAdmin = false,
                            LastName = "Doe",
                            Password = "password123",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jane",
                            IsAdmin = false,
                            LastName = "Smith",
                            Password = "password456",
                            Username = "janesmith"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Alice",
                            IsAdmin = false,
                            LastName = "Johnson",
                            Password = "password789",
                            Username = "alicejohnson"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Bob",
                            IsAdmin = false,
                            LastName = "Brown",
                            Password = "password101",
                            Username = "bobbrown"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Employee", b =>
                {
                    b.HasOne("DataLayer.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Models.Reward", b =>
                {
                    b.HasOne("DataLayer.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
